name = "hono-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = ""
localConnectionString = ""

[[r2_buckets]]
binding = "BUCKET"
bucket_name = ""
preview_bucket_name = ""



